export * from './home/home.page';
export * as termsPage from './terms/terms.page';
export * from './login/login.page';
export * from './donate/donate.page';
export * from './offline/offline.page';
export * from './add-word/add-word.page';
export * as notFoundPage from './not-found/not-found.page';
export * from './find-word/find-word.page';
export * from './dashboard/dashboard.page';
export * from './onboarding/onboarding.page';
export * as privacyPolicyPage from './privacy-policy/privacy-policy.page';
export * from './account-settings/account-settings.page';
