import Head from 'next/head';
import { FC } from 'react';

import { Button, Heading, Input, Text } from '@ui/atoms';
import { SidebarWithHeader } from '@ui/organisms';

import { useUser } from '@infrastructure/utils';

export const HomePage: FC = (): JSX.Element => {
  const { isUserAuthenticated, loginViaGoogle, logout } = useUser();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
      </Head>
      <SidebarWithHeader>
        <h1 className="block bg-slate-300 text-4xl leading-tight">Test</h1>
        <Heading>Test</Heading>
        {!isUserAuthenticated ? (
          <Button onClick={loginViaGoogle}>Login</Button>
        ) : (
          <Button onClick={logout}>Logout</Button>
        )}
        <Input />
        <Text>Test</Text>
      </SidebarWithHeader>
    </div>
  );
};
