import Head from 'next/head';
import { FC } from 'react';

import { Heading, Input, Text } from '@ui/atoms';

export const HomePage: FC = (): JSX.Element => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta content="Generated by create next app" name="description" />
    </Head>
    <main>
      <h1 className="block bg-slate-300 text-4xl leading-tight">Test</h1>
      <Heading>Test</Heading>
      <Input />
      <Text>Test</Text>
    </main>
  </div>
);
