import Head from 'next/head';
import { FC } from 'react';

import { SidebarWithHeader } from '@ui/organisms';
import { HomeTemplate } from '@ui/templates';

export const HomePage: FC = (): JSX.Element => (
  <>
    <Head>
      <title>Levofron</title>
      <meta content="Generated by create next app" name="description" />
    </Head>
    <SidebarWithHeader />
    <HomeTemplate />
  </>
);
