import Head from 'next/head';

export default function Home() {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <h1 className="text-4xl">Test</h1>
      </main>
    </div>
  );
}
