import { Button, Heading } from '@chakra-ui/react';
import Head from 'next/head';

import { authorizationExecutors } from '@adapter/executors/authorization.executors';

export default function Home() {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
      </Head>
      <main>
        <h1 className="block bg-slate-300 text-4xl leading-tight">Test</h1>
        <Heading>Test</Heading>
      </main>
      <Button onClick={() => authorizationExecutors.loginViaGoogle()}>Login</Button>
      <Button onClick={() => authorizationExecutors.logout()}>Logout</Button>
    </div>
  );
}
