export const APP_NAME = 'Levofron';
export const WEBSITE_URL = 'https://levofron.com';
export const DEFAULT_DESCRIPTION =
  'Elevate your vocabulary with our cutting-edge app! Our intuitive platform allows you to easily learn new words and phrases from your own Notion database!';

export const SEO_KEYWORDS = [
  'english vocabulary',
  'notion database',
  'language learning',
  'vocabulary builder',
  'word memorization',
  'english language education',
  'study tool',
  'personalized learning',
  'flashcard system',
  'user-friendly',
  'efficient vocabulary acquisition',
  'enhancing language skills',
  'innovative learning approach',
  'vocabulary development',
  'boost language proficiency',
  'language learning app',
  'language learning platform',
  'language learning software',
  'language learning tool',
  'language learning website',
  'english',
  'vocabluary',
  'notion',
  'database',
  'learning',
  'language',
  'builder',
  'vocabulary',
  'memorization',
  'education',
  'tool',
  'personalized',
  'flashcard',
  'system',
  'user-friendly',
  'efficient',
  'acquisition',
  'enhancing',
  'skills',
  'innovative',
  'approach',
  'development',
  'boost',
  'proficiency',
  'app',
  'platform',
  'software',
  'website',
];
