name: CI

on: [pull_request]

jobs:
  pull-request:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Typecheck
        run: yarn typecheck

      - name: Prettier
        run: yarn format:check
